name: Test and Deploy

on: [push, pull_request]

env:
  DOCKER_USERNAME: tobiaszimmer

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Run unit tests
        run: mvn test

      - name: Run integration tests
        run: mvn verify

#      - name: Run mutation tests
#        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage

      - name: Package
        run: mvn package -Dmaven.test.skip=true

      - name: Setup variables
        run: |
          sudo apt install libxml-xpath-perl -y
          version=$(. scripts/get_xpath_value.sh 'pom.xml' 'project/version')
          lower_case_image=$(echo $IMAGE_NAME | awk '{print tolower($0)}')
          echo "project_version=$version" >> $GITHUB_ENV
          echo "lower_case_image=$lower_case_image" >> $GITHUB_ENV
          echo "branch_name=$(echo $GITHUB_REF | cut -d'/' -f 3 | tr / -)" >> $GITHUB_ENV
        env:
          IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}

      - name: Deploy to dockerhub
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
          name=$(. scripts/get_xpath_value.sh 'pom.xml' 'project/name')
          jar_file="target/$name-$project_version.jar"
          image="$lower_case_image:$branch_name-$project_version"
          docker build --build-arg jar_file=$jar_file --tag "$image" .
          docker push "$image"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: ${{ env.lower_case_image }}
          provider: dockerhub
          short_description: "Awesome Microservice"
          readme_file: "DOCKER_README.md"
